# Plugins
services:
    # Object plugins
    casebox_core.service_objects_plugins.base:
        class: Casebox\CoreBundle\Service\Objects\Plugins\Base

    casebox_core.service_objects_plugins.comments:
        class: Casebox\CoreBundle\Service\Objects\Plugins\Comments

    casebox_core.service_objects_plugins.contentItems:
        class: Casebox\CoreBundle\Service\Objects\Plugins\ContentItems

    casebox_core.service_objects_plugins.currentVersion:
        class: Casebox\CoreBundle\Service\Objects\Plugins\CurrentVersion

    casebox_core.service_objects_plugins.files:
        class: Casebox\CoreBundle\Service\Objects\Plugins\Files

    casebox_core.service_objects_plugins.html:
        class: Casebox\CoreBundle\Service\Objects\Plugins\Html

    casebox_core.service_objects_plugins.meta:
        class: Casebox\CoreBundle\Service\Objects\Plugins\Meta

    casebox_core.service_objects_plugins.objectProperties:
        class: Casebox\CoreBundle\Service\Objects\Plugins\ObjectProperties

    casebox_core.service_objects_plugins.system_properties:
        class: Casebox\CoreBundle\Service\Objects\Plugins\SystemProperties

    casebox_core.service_objects_plugins.tasks:
        class: Casebox\CoreBundle\Service\Objects\Plugins\Tasks

    casebox_core.service_objects_plugins.thumb:
        class: Casebox\CoreBundle\Service\Objects\Plugins\Thumb

    casebox_core.service_objects_plugins.timetracking:
        class: Casebox\CoreBundle\Service\Objects\Plugins\TimeTracking

    casebox_core.service_objects_plugins.versions:
        class: Casebox\CoreBundle\Service\Objects\Plugins\Versions

    # Core plugins
    casebox_core.service_plugins.auto_set_fields:
        class: Casebox\CoreBundle\Service\Plugins\AutoSetFields

    casebox_core.service_plugins.system_folders:
        class: Casebox\CoreBundle\Service\Plugins\SystemFolders

    # Display column
    casebox_core.service_plugins_display_columns.display_columns:
        class: Casebox\CoreBundle\Service\Plugins\DisplayColumns\DisplayColumns
        calls:
            - [setContainer, ['@service_container']]

    casebox_core.service_plugins_display_columns.activityStream:
        class: Casebox\CoreBundle\Service\Plugins\DisplayColumns\ActivityStream

    casebox_core.service_plugins_display_columns.base:
        class: Casebox\CoreBundle\Service\Plugins\DisplayColumns\Base

    casebox_core.service_plugins_display_columns.calendar:
        class: Casebox\CoreBundle\Service\Plugins\DisplayColumns\Calendar

    casebox_core.service_plugins_display_columns.formEditor:
        class: Casebox\CoreBundle\Service\Plugins\DisplayColumns\FormEditor

    casebox_core.service_plugins_display_columns.grid:
        class: Casebox\CoreBundle\Service\Plugins\DisplayColumns\Grid

    casebox_core.service_plugins_display_columns.map:
        class: Casebox\CoreBundle\Service\Plugins\DisplayColumns\Map
